package com.example.myappjwt.db_hungha2.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.myappjwt.db_hungha2.model.User;
import com.example.myappjwt.db_hungha2.model.UserExample;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_hungha2.auth_user
     *
     * @mbg.generated Wed Sep 25 09:14:02 ICT 2024
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_hungha2.auth_user
     *
     * @mbg.generated Wed Sep 25 09:14:02 ICT 2024
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_hungha2.auth_user
     *
     * @mbg.generated Wed Sep 25 09:14:02 ICT 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_hungha2.auth_user
     *
     * @mbg.generated Wed Sep 25 09:14:02 ICT 2024
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_hungha2.auth_user
     *
     * @mbg.generated Wed Sep 25 09:14:02 ICT 2024
     */
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_hungha2.auth_user
     *
     * @mbg.generated Wed Sep 25 09:14:02 ICT 2024
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_hungha2.auth_user
     *
     * @mbg.generated Wed Sep 25 09:14:02 ICT 2024
     */
    User selectByPrimaryKey(Long id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_hungha2.auth_user
     *
     * @mbg.generated Wed Sep 25 09:14:02 ICT 2024
     */
    int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_hungha2.auth_user
     *
     * @mbg.generated Wed Sep 25 09:14:02 ICT 2024
     */
    int updateByExample(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_hungha2.auth_user
     *
     * @mbg.generated Wed Sep 25 09:14:02 ICT 2024
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_hungha2.auth_user
     *
     * @mbg.generated Wed Sep 25 09:14:02 ICT 2024
     */
    int updateByPrimaryKey(User row);
}